### ISSUE TITLE
Using this plugin doesn't fix the IP issue when publishing from Travis CI to oss.sonatype.org 

### ISSUE THREAD

**Issue by bartoszwalacik** [marcphilipp/nexus-publish-plugin#13] opened 2018-12-23 17:53 UTC
Hi guys, I'm trying to fix my CI/CD pipeline after Travis changed its infrastructure from docker to VMs, which broke many of our builds.

The issue:
https://github.com/gradle/gradle/issues/5711
https://github.com/travis-ci/travis-ci/issues/9555

As far as I understand, this plugin is designed to fix this issue. I tried to used it but without success. I still got the same error on Travis:

```
Requested operation wasn't successful in first try. Retrying maximum 20 times with 3 seconds delay between attempts.
Attempt 1/21 failed. WrongNumberOfRepositories was thrown with message 'Wrong number of received repositories in state 'open'. Expected 1, received 8'. Waiting 3000 ms before next retry.
```

I'm using `maven-publish` plugin and @szpak 's `gradle-nexus-staging-plugin`.

My build.gradle: https://github.com/javers/javers/blob/master/build.gradle
and the commit which applies the new plugin: https://github.com/javers/javers/commit/e91566a66d5f6d86a9ee48a3a333fd5a0fd4c15c

I'm not the Gradle master like you guys. I just want to fix my pipeline, what is missing in my `build.gradle`?

**Comment by szpak** [comment] 2018-12-23 19:13
> Expected 1, received 8

It may be not related, but have you removed all pending staging repositories before triggering that release?

**Comment by szpak** [comment] 2018-12-23 19:30
There's something strange with your build. You apply the `maven-publish` plugin, but also `com.bmuschko.nexus` which under the hood uses the old `maven` plugin. In your Travis log there are tasks (such as `uploadArchives`) which seem to suggest that you are using the old `maven` plugin to upload the archives. In that case you may hit #8. However, it's @marcphilipp's plugin and I may miss something.

**Comment by marcphilipp** [comment] 2018-12-26 14:55
@bartoszwalacik Which Gradle task did you call to publish?

**Comment by bartoszwalacik** [comment] 2018-12-27 15:08
@szpak yes, I've removed all pending staging repositories

@marcphilipp I call
```
./gradlew uploadArchives
```

and then 

```
./gradlew closeAndReleaseRepository
```

see https://github.com/javers/javers/blob/master/travis/deployToSonatype.sh

**Comment by marcphilipp** [comment] 2019-01-01 17:36
@bartoszwalacik The `uploadArchives` task is part of the old `Upload` task based publishing infrastructure that is not (yet) supported by this plugin.

**Comment by marcphilipp** [comment] 2019-01-01 17:36
Duplicate of #8

**Closed as completed by marcphilipp** 2019-01-01 17:36 UTC
Labels: question

**Comment by bartoszwalacik** [comment] 2019-01-02 07:31
@marcphilipp so which task should I call?

**Comment by marcphilipp** [comment] 2019-01-02 08:14
The `publish` task (see https://docs.gradle.org/current/userguide/publishing_maven.html).

**Comment by bartoszwalacik** [comment] 2019-01-02 13:56
thanks
